### ISSUE TITLE
Hardware ToDo

### ISSUE THREAD

**Issue by danngreen** [4ms/metamodule#24]
- [ ] Expander headers
- [ ] Header for Wi-fi board (SPI)
- [ ] Position of screen connector: as-is, slide back a few mm, or on reverse side (bottom contact)
- [ ] SD card routing supports sustained fast speed?
- [ ] Mounting holes for Wurth snap ins
- [ ] Faceplate: Sd slot, new mounting holes, usb location, colors brighter
